version: '3.8'

services:
  broker-service:
    build:
      context: ../services/broker-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - product-service
      - payment-service

  product-service:
    build:
      context: ../services/product-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:80"
    environment:
      - DSN=host=postgres port=5432 user=postgres password=password dbname=product_service sslmode=disable timezone=UTC connect_timeout=5
    depends_on:
      - postgres

  payment-service:
    build:
      context: ../services/payment-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:80"
    environment:
      - DSN=host=postgres port=5432 user=postgres password=password dbname=payment_service sslmode=disable timezone=UTC connect_timeout=5
    depends_on:
      - postgres
  order-service:
    build:
      context: ../services/order-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8083:80"   
    environment:
      - MONGO_URI=mongodb://mongo:27017/order_service
      - USER_SERVICE_URL=http://localhost:8100/user-service/api/users  
    depends_on:
      - mongo
      - product-service
      - payment-service

  notification-service:
    build:
      context: ../services/notification-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8084:8080"
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=notifications
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./db-data/rabbitmq:/var/lib/rabbitmq

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=order_service
    volumes:
      - ./db-data/mongo:/data/db
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_service
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
